"""empty message

Revision ID: 30692705010d
Revises: be22d0a449d8
Create Date: 2024-07-30 16:21:46.576187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30692705010d'
down_revision = 'be22d0a449d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acc_rooms',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('room_code', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('accounts',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('pid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    op.drop_table('acc_rooms')
    # ### end Alembic commands ###
