"""empty message

Revision ID: be22d0a449d8
Revises: f9b418cdaf90
Create Date: 2024-07-30 16:14:07.623272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be22d0a449d8'
down_revision = 'f9b418cdaf90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    op.drop_table('acc_rooms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acc_rooms',
    sa.Column('pk', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('room_code', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('accounts',
    sa.Column('pid', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('pid')
    )
    # ### end Alembic commands ###
