"""empty message

Revision ID: cf65386631e2
Revises: 0d7b7e0c3621
Create Date: 2024-08-06 16:34:54.699032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf65386631e2'
down_revision = '0d7b7e0c3621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_fr_request',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('sender', sa.Text(), nullable=False),
    sa.Column('receiver', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_fr_request')
    # ### end Alembic commands ###
