"""empty message

Revision ID: f9b418cdaf90
Revises: 8524e054b802
Create Date: 2024-07-29 17:46:00.235519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9b418cdaf90'
down_revision = '8524e054b802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acc_rooms',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('room_code', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acc_rooms')
    # ### end Alembic commands ###
